/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BestsellersRouteImport } from './routes/bestsellers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ClothingRouteImport } from './routes/clothing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as JewelleryRouteImport } from './routes/jewellery'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as WeddingRouteImport } from './routes/wedding'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsHandleRouteImport } from './routes/collections.$handle'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BestsellersRoute = BestsellersRouteImport.update({
  id: '/bestsellers',
  path: '/bestsellers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ClothingRoute = ClothingRouteImport.update({
  id: '/clothing',
  path: '/clothing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryRoute = JewelleryRouteImport.update({
  id: '/jewellery',
  path: '/jewellery',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingRoute = WeddingRouteImport.update({
  id: '/wedding',
  path: '/wedding',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/bestsellers': typeof BestsellersRoute
  '/cart': typeof CartRoute
  '/clothing': typeof ClothingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/jewellery': typeof JewelleryRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wedding': typeof WeddingRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/bestsellers': typeof BestsellersRoute
  '/cart': typeof CartRoute
  '/clothing': typeof ClothingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/jewellery': typeof JewelleryRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wedding': typeof WeddingRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/collections': typeof CollectionsIndexRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/bestsellers': typeof BestsellersRoute
  '/cart': typeof CartRoute
  '/clothing': typeof ClothingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/jewellery': typeof JewelleryRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wedding': typeof WeddingRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/bestsellers'
    | '/cart'
    | '/clothing'
    | '/contact'
    | '/faq'
    | '/jewellery'
    | '/new-arrivals'
    | '/privacy'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/terms'
    | '/track-order'
    | '/wedding'
    | '/wishlist'
    | '/collections/$handle'
    | '/journal/$slug'
    | '/products/$handle'
    | '/collections/'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/bestsellers'
    | '/cart'
    | '/clothing'
    | '/contact'
    | '/faq'
    | '/jewellery'
    | '/new-arrivals'
    | '/privacy'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/terms'
    | '/track-order'
    | '/wedding'
    | '/wishlist'
    | '/collections/$handle'
    | '/journal/$slug'
    | '/products/$handle'
    | '/collections'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/bestsellers'
    | '/cart'
    | '/clothing'
    | '/contact'
    | '/faq'
    | '/jewellery'
    | '/new-arrivals'
    | '/privacy'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/terms'
    | '/track-order'
    | '/wedding'
    | '/wishlist'
    | '/collections/$handle'
    | '/journal/$slug'
    | '/products/$handle'
    | '/collections/'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BestsellersRoute: typeof BestsellersRoute
  CartRoute: typeof CartRoute
  ClothingRoute: typeof ClothingRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  JewelleryRoute: typeof JewelleryRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WeddingRoute: typeof WeddingRoute
  WishlistRoute: typeof WishlistRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestsellers': {
      id: '/bestsellers'
      path: '/bestsellers'
      fullPath: '/bestsellers'
      preLoaderRoute: typeof BestsellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clothing': {
      id: '/clothing'
      path: '/clothing'
      fullPath: '/clothing'
      preLoaderRoute: typeof ClothingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery': {
      id: '/jewellery'
      path: '/jewellery'
      fullPath: '/jewellery'
      preLoaderRoute: typeof JewelleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding': {
      id: '/wedding'
      path: '/wedding'
      fullPath: '/wedding'
      preLoaderRoute: typeof WeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BestsellersRoute: BestsellersRoute,
  CartRoute: CartRoute,
  ClothingRoute: ClothingRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  JewelleryRoute: JewelleryRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  WeddingRoute: WeddingRoute,
  WishlistRoute: WishlistRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
